version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase
    reviewers:
      - andrcuns
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - andrcuns
